document.addEventListener('DOMContentLoaded', () => {
        // Smooth scrolling for navigation links
            document.querySelectorAll('a[href^="#"]').forEach(anchor => {
                    anchor.addEventListener('click', function(e) {
                                e.preventDefault();
                                            document.querySelector(this.getAttribute('href')).scrollIntoView({
                                                            behavior: 'smooth'
                                                                        });
                                                                                });
                                                                                    });

                                                                                        // Form submission handling
                                                                                            const contactForm = document.getElementById('contactForm');
                                                                                                const formStatus = document.getElementById('formStatus');

                                                                                                    contactForm.addEventListener('submit', function(e) {
                                                                                                            e.preventDefault(); // Prevent default form submission

                                                                                                                    // In a real-world scenario, you would send this data to a backend server.
                                                                                                                            // For this static site, we'll just simulate a successful submission.
                                                                                                                                    
                                                                                                                                            const formData = new FormData(contactForm);
                                                                                                                                                    const name = formData.get('name');
                                                                                                                                                            
                                                                                                                                                                    // Simulate an API call
                                                                                                                                                                            formStatus.textContent = "Submitting your issue...";
                                                                                                                                                                                    formStatus.style.color = '#007bff';
                                                                                                                                                                                            
                                                                                                                                                                                                    setTimeout(() => {
                                                                                                                                                                                                                // Success message
                                                                                                                                                                                                                            formStatus.textContent = `Thanks, ${name}! Your issue has been submitted. We'll be in touch soon.`;
                                                                                                                                                                                                                                        formStatus.style.color = '#28a745';
                                                                                                                                                                                                                                                    contactForm.reset();
                                                                                                                                                                                                                                                            }, 1500); // Wait 1.5 seconds to simulate loading
                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                    // Intersection Observer for animations
                                                                                                                                                                                                                                                                        // This makes the sections animate as they come into view
                                                                                                                                                                                                                                                                            const observerOptions = {
                                                                                                                                                                                                                                                                                    root: null,
                                                                                                                                                                                                                                                                                            rootMargin: '0px',
                                                                                                                                                                                                                                                                                                    threshold: 0.1
                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                            const sectionObserver = new IntersectionObserver((entries, observer) => {
                                                                                                                                                                                                                                                                                                                    entries.forEach(entry => {
                                                                                                                                                                                                                                                                                                                                if (entry.isIntersecting) {
                                                                                                                                                                                                                                                                                                                                                const elementsToAnimate = entry.target.querySelectorAll('.service-card, .step-card, .contact-form');
                                                                                                                                                                                                                                                                                                                                                                elementsToAnimate.forEach(el => el.style.opacity = '1');
                                                                                                                                                                                                                                                                                                                                                                                observer.unobserve(entry.target);
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                        }, observerOptions);

                                                                                                                                                                                                                                                                                                                                                                                                            document.querySelectorAll('section').forEach(section => {
                                                                                                                                                                                                                                                                                                                                                                                                                    if(section.id !== 'hero') { // Hero section is already animated
                                                                                                                                                                                                                                                                                                                                                                                                                                sectionObserver.observe(section);
                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                            });

